openapi: 3.0.2
info:
  title: 'Statistikk-api-dokumentasjon'
  version: 'Spekkhoggern_v.1'
servers:
- url: https://statistics-api.azurewebsites.net
  description: The production API server
- url: https://statistics-api-staging.azurewebsites.net
  description: The staging API server

paths:
  /api/statistics/user_activity/:
    get:
      operationId: listEnrollmentActivityViewSets
      description: This api call fetches enrollment activity for the entirety of "kompetanse.udir.no". It is necessary to specify to/from dates. This makes it so that the amount of data requested isnt overwhelming. 
      parameters:
        - name: from
          in: query
          required: true
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string

      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''

      tags:
      - User_activity
  /api/statistics/user_activity/{course_id}/:
    get:
      operationId: retrieveEnrollmentActivityViewSet
      description: A enrollment ViewSet for listing or retrieving enrollment activity based on the course_id. You can choose to/from dates to further specify what timeperiod you want to see the enrollment acitivty. 
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - User_activity
  /api/statistics/{course_id}/:
    get:
      description: View enrollment count for a course and number of associated groups aggregated by group category. Here you will see how many indiviuals are enrolled per course. With associated groups and their memeber_count, canvas_id and subgroups. This call requires a to/from date to be able to fetch the data. Otherwise the data-amount is overwhelming.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: true
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Course_id
  /api/statistics/{course_id}/count:
    get:
      description: View enrollment count for a course. Here you will see how many people are enrolled in the course. You can also specify which to/from data to narrow down the timeperiod in which the enrollment happened. 
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Course_id
  /api/statistics/groupCategory/{group_category_id}:
    get:
      description: View all Canvas LMS groups associated with a group category. Here you will find all groups that exist within a specifc group category. By using the group_category_id which can be found in "kompetanse.udir.no" under "people". You can limit the search by using to/from dates if you want to see number of groups in a specific timeline. Member count for groups wih 5 or fewer members will be anonymized and show a member count = 0.  
      parameters:
        - name: group_category_id
          in: path
          required: true
          description: 'Canvas LMS group category ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: aggregated
          in: query
          required: false
          description: 'Aggregated true will limit the results to groups with 5 or fewer members. Aggregated false will limit result to groups with more than 5 members. Not included will show all groups.'
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Group_category_id
  /api/statistics/groupCategory/{group_category_id}/count:
    get:
      description: View the number of Canvas LMS groups associated with a group category. Here you will find a summary of the number of canvas LMS groups associated wit a specific group_category_id. You can limit the search by using to/from dates if you want to see number of groups in a specific timeline. 
      parameters:
        - name: group_category_id
          in: path
          required: true
          description: 'Canvas LMS group category ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Group_category_id
  /api/statistics/primary_schools/municipality/{municipality_id}/course/{course_id}:
    get:
      description: View enrollment percentage of teachers at primary schools in specified municipality. Here you will find the enrollment percentage category of techers at primary schools in a specified munciilaity and course. You can limit the search by using to/from dates if you want see a specific timeline. Likewise you can also limit the search by specifying what enrollment_percentage_categories you want filtered. 
      parameters:
        - name: municipality_id
          in: path
          required: true
          description: 'Official municipality ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: enrollment_percentage_categories
          in: query
          required: false
          description: 'Filter which enrollment percentage categories appear in result. E.g. enrollment_percentage_categories=1,2,3'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Municipality
  /api/statistics/primary_schools/county/{county_id}/course/{course_id}:
    get:
      description: View enrollment percentage of teachers at primary schools in specified county. Here you will find the enrollment percentage category of techers at primary schools in a specified county and course. You can limit the search by using to/from dates if you want see a specific timeline. Likewise you can also limit the search by specifying what enrollment_percentage_categories you want filtered. The last filter oppertunity in this call is to either show schools. Showing schools gives you the data displayed on school level, disbeling this gives you a overview on the municipality level.  
      parameters:
        - name: county_id
          in: path
          required: true
          description: 'Official county ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: enrollment_percentage_categories
          in: query
          required: false
          description: 'Filter which enrollment percentage categories appear in result. E.g. enrollment_percentage_categories=1,2,3'
          schema:
            type: string
        - name: show_schools
          in: query
          required: false
          description: 'Enable data for individual schools. If false, data is aggregated by municipalities.'
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - County
  /api/statistics/high_schools/county/{county_id}/course/{course_id}:
    get:
      description: View enrollment percentage of high schools teachers in specified county. Here you will find the data for high_schools in a specified county and course id.  You can limit the search by using to/from dates if you want so see a specific timeline. 
      parameters:
        - name: county_id
          in: path
          required: true
          description: 'Official county ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - County
  /api/statistics/course/{course_id}/quizzes:
    get:
      description: View statistics for all quizzes in a specified course. Here you will find number of responses on answeralternatives for questions in the quizzes. You will also see response count per group.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Quiz
  /api/statistics/course/{course_id}/quiz/{quiz_id}:
    get:
      description: View statistics for a specicfied quiz in a specified course. Here you will find number of responses on answeralternatives for questions in the specified quiz. You will also see response count per group. 
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: quiz_id
          in: path
          required: true
          description: 'Canvas LMS quiz ID'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Quiz
  /api/statistics/visits:
    get:
      description: View total visist statistics. Here you will find statitistics for each date (opptionally specified between two dates), information includes unique visits, returning visitors, sum length of all visits etc.
      parameters:
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Visitors_statistics
  /api/statistics/pages:
    get:
      description: View total visist statistics for each page. Here you will find statitistics for each date (opptionally specified between two dates), information includes unique visits, returning visitors, sum length of all visits etc. Lots of data, recommended specifying dates. 
      parameters:
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Visitors_statistics
  /api/statistics/course/{course_id}/pages:
    get:
      description: View total visist statistics for each page in a specified course. Here you will find statitistics for each date (opptionally specified between two dates), information includes unique visits, returning visitors, sum length of all visits etc.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Visitors_statistics
  /api/statistics/{course_id}/modules:
    get:
      description: View finnish marks per group for module items in a course. Here you will see how many people per group in the course that has completed each module item.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - Modules    