openapi: 3.0.2
info:
  title: 'statistics API Documentation'
  version: 'version: Spekkhoggern'
servers:
- url: https://statistics-api.azurewebsites.net
  description: The production API server
- url: https://statistics-api-staging.azurewebsites.net
  description: The staging API server
paths:
  /api/statistics/user_activity/:
    get:
      operationId: listEnrollmentActivityViewSets
      description: A enrollment ViewSet for listing or retrieving enrollment activity. This call fetches the entire history of all enrollments activities for kompetanse.udir.no. It is necessary to specify to/from date. Otherwise the call will fail. 
      parameters: []       
        
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /api/statistics/user_activity/{course_id}/:
    get:
      operationId: retrieveEnrollmentActivityViewSet
      description: A enrollment ViewSet for listing or retrieving enrollment activity. This call fetches the entire history of user activity for the specified course. Its adviced to specify to/from date's for the call so that the data is more approcable. 
      parameters:
      - - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/{course_id}/:
    get:
      description: View enrollment count for a course and number of associated groups aggregated by group category.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/{course_id}/count:
    get:
      description: View enrollment count for a course.
      parameters:
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/groupCategory/{group_category_id}:
    get:
      description: View all Canvas LMS groups associated with a group category
      parameters:
        - name: group_category_id
          in: path
          required: true
          description: 'Canvas LMS group category ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/groupCategory/{group_category_id}/count:
    get:
      description: View the number of Canvas LMS groups associated with a group category
      parameters:
        - name: group_category_id
          in: path
          required: true
          description: 'Canvas LMS group category ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/primary_schools/municipality/{municipality_id}/course/{course_id}:
    get:
      description: View enrollment percentage of teachers at primary schools in specified municipality
      parameters:
        - name: municipality_id
          in: path
          required: true
          description: 'Official municipality ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: enrollment_percentage_categories
          in: query
          required: false
          description: 'Filter which enrollment percentage categories appear in result. E.g. enrollment_percentage_categories=1,2,3'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/primary_schools/county/{county_id}/course/{course_id}:
    get:
      description: View enrollment percentage of teachers at primary schools in specified county
      parameters:
        - name: county_id
          in: path
          required: true
          description: 'Official county ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: enrollment_percentage_categories
          in: query
          required: false
          description: 'Filter which enrollment percentage categories appear in result. E.g. enrollment_percentage_categories=1,2,3'
          schema:
            type: string
        - name: show_schools
          in: query
          required: false
          description: 'Enable data for individual schools. If false, data is aggregated by municipalities.'
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/statistics/high_schools/county/{county_id}/course/{course_id}:
    get:
      description: View enrollment percentage of high schools teachers in specified county
      parameters:
        - name: county_id
          in: path
          required: true
          description: 'Official county ID'
          schema:
            type: string
        - name: course_id
          in: path
          required: true
          description: 'Canvas LMS course ID'
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 'Limit results to dates later than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
        - name: to
          in: query
          required: false
          description: 'Limit results to earlier than specified date. Format is YYYY-MM-DD.'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
